version: '3.1'

networks:
  api:

services:
  db:
    build: 
      dockerfile: ./Dockerfile.db.dev
    container_name: message-api-clean-arch_db
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - api

  api:
    build:
      dockerfile: ./Dockerfile.node.dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: ["yarn", "start:dev"]
    depends_on:
      - db
    networks:
      - api